### ISSUE TITLE
I want to contribute to this project. Need help for getting started.

### ISSUE THREAD

**Issue by ukpa** [dan-c-underwood/language-arm#4]

**Comment by dan-c-underwood** [comment]
Hi - I'm happy to provide some guidance. What would you be wanting to add to the project?

**Comment by ukpa** [comment]
I want to add support for as many instructions as possible including 32/64/thumb ISA. Also i was thinking about adding a new color scheme which feels natural to eyes.

**Comment by dan-c-underwood** [comment]
New colour schemes are covered in the Atom flight manual: http://flight-manual.atom.io/hacking-atom/sections/creating-a-theme/

You'll need to create your own separate package to add one.

In terms of adding support for more instructions to this package, you'll need to edit the regular expressions in `grammars/arm.cson`. If you're new to regular expressions then I'd suggest using a site such as https://regex101.com/ to help you understand how the current regex work.

In terms of where instructions go:
* storage.other.register.arm: is for anything register related
* support.mnemonic.arithmetic.arm: is for arithmetic instructions 
* support.mnemonic.memory.arm: is for memory related instructions
* keyword.control.*: are for any keywords

Hope that helps!
