### ISSUE TITLE
Feature Request: Setting for changing the comment symbol

### ISSUE THREAD

**Issue by robbycbennett** [dan-c-underwood/language-arm#7]
For example, I want to change it from the at symbol @ to the double slash //

I know that the syntax coloring works, but it would be nice if I could change the default comment symbol for when I comment out multiple lines.

**Comment by dan-c-underwood** [comment]
Fixed in v2.0.0. I've just pulled in the changes from https://github.com/dan-c-underwood/vscode-arm. Let me know if you spot any issues.
